
import React, { useRef } from 'react'
import { GlobalWorkerOptions } from 'pdfjs-dist/legacy/build/pdf'
import pdfWorkerUrl from 'pdfjs-dist/legacy/build/pdf.worker.min.mjs?url'
import { Card } from '../ui'
import { useProof } from '../../hooks/api/proof'
import { useAuthStore, useUIStore } from '../../store'
import {
  buildWorkbenchSectionsProps,
} from './sovereign/panelPropsBuilders'
import SovereignWorkbenchSections from './sovereign/SovereignWorkbenchSections'
import { useSovereignAdvancedOps } from './sovereign/useSovereignAdvancedOps'
import { useSovereignArView } from './sovereign/useSovereignArView'
import { useSovereignEvidencePanelState } from './sovereign/useSovereignEvidencePanelState'
import { useSovereignEvidenceDerivedState } from './sovereign/useSovereignEvidenceDerivedState'
import { useSovereignContextActions } from './sovereign/useSovereignContextActions'
import { useSovereignGeoSpecdictState } from './sovereign/useSovereignGeoSpecdictState'
import { useSovereignWorkbenchInputState } from './sovereign/useSovereignWorkbenchInputState'
import { useSovereignWorkbenchSummaryState } from './sovereign/useSovereignWorkbenchSummaryState'
import {
  useSovereignProofChainInputs,
  useSovereignProofChainStatus,
} from './sovereign/useSovereignProofChainState'
import {
  useSovereignActiveGenesisSummary,
  useSovereignTreeDerivedState,
} from './sovereign/useSovereignTreeDerivedState'
import { useSovereignTreeImport } from './sovereign/useSovereignTreeImport'
import { useSovereignConsensusState } from './sovereign/useSovereignConsensusState'
import { useSovereignTripFlow, useSovereignTripFlowState } from './sovereign/useSovereignTripFlow'
import { useSovereignWorkbenchActions } from './sovereign/useSovereignWorkbenchActions'
import { useSovereignWorkbenchLocalState } from './sovereign/useSovereignWorkbenchLocalState'
import {
  useDocPegPreviewEffects,
  useGeoFenceToastEffect,
  useWorkspaceSnapshotEffect,
} from './sovereign/useSovereignWorkbenchEffects'
import {
  useActiveNodeBroadcastEffect,
  useDisputeProofAutofillEffect,
  useLabRefreshEffect,
  useNowTickEffect,
  useSovereignVerifyAssets,
} from './sovereign/useSovereignWorkbenchSupport'
import { useSovereignWorkbenchViewState } from './sovereign/useSovereignWorkbenchViewState'
import {
  describeSpecdictItem,
} from './sovereign/analysisUtils'
import {
  downloadJson,
} from './sovereign/fileUtils'
import { NormEngineProvider } from './sovereign/NormEngine'
import type { SovereignWorkspaceSnapshot, SovereignWorkspaceView } from './sovereign/SovereignProjectContext'
import { ProjectSovereignProvider } from './sovereign/SovereignContext'
import {
  buildMeasurementPayload,
  sanitizeMeasuredInput,
  toChineseCompType,
  toChineseMetricLabel,
} from './sovereign/spuUtils'
import {
  formatNumber,
  toApiUri,
  toDisplayUri,
} from './sovereign/treeUtils'
import { useAuditFinalizeActions } from './sovereign/useAuditFinalizeActions'
import { useEvidenceCenterLoader } from './sovereign/useEvidenceCenterLoader'
import { useEvidenceEventLogs } from './sovereign/useEvidenceEventLogs'
import { useEvidenceCenterView } from './sovereign/useEvidenceCenterView'
import { useEvidenceFiles } from './sovereign/useEvidenceFiles'
import { useOfflinePackets } from './sovereign/useOfflinePackets'
import { useScanConfirmAction } from './sovereign/useScanConfirmAction'
import { useScanEntryState } from './sovereign/useScanEntryState'
import { useSpecdictArActions } from './sovereign/useSpecdictArActions'
import { useSovereignSession } from './sovereign/useSovereignSession'
import { useSovereignP2PManifestExport } from './sovereign/useSovereignP2PManifestExport'
import {
  OFFLINE_KEY,
  WORKBENCH_FRAME_STYLE_TEXT,
  WORKBENCH_GRID_OVERLAY_STYLE,
} from './sovereign/workbenchConfig'
import { buildSovereignWorkbenchDisplayState } from './sovereign/workbenchDisplayState'
import { asWorkbenchDict, buildDraftPdfBase64 } from './sovereign/workbenchPdfUtils'
import { buildSovereignWorkbenchSectionHandlers } from './sovereign/workbenchSectionHandlers'
import {
  buildSovereignWorkbenchSecondary,
  buildSovereignWorkbenchSecondaryAuditShell,
  buildSovereignWorkbenchSecondaryEvidenceModal,
  buildSovereignWorkbenchSecondaryEvidenceVault,
  buildSovereignWorkbenchSecondaryOfflineFooter,
  buildSovereignWorkbenchSecondaryOverlay,
  buildSovereignWorkbenchSecondaryStylePacks,
  buildSovereignWorkbenchSecondaryTripFlowModal,
} from './sovereign/workbenchSecondaryBuilders'
import {
  buildSovereignWorkbenchPrimary,
  buildSovereignWorkbenchShell,
} from './sovereign/workbenchPrimaryBuilders'

type Props = {
  project: { id?: string; v_uri?: string; name?: string } | null
  workspaceView?: SovereignWorkspaceView
  onNavigateView?: (view: SovereignWorkspaceView) => void
  onContextChange?: (snapshot: SovereignWorkspaceSnapshot) => void
}

try {
  GlobalWorkerOptions.workerSrc = pdfWorkerUrl
} catch {
  // ignore worker setup failures in non-browser env
}

export default function SovereignWorkbenchPanel({
  project,
  workspaceView = 'trip',
  onNavigateView,
  onContextChange,
}: Props) {
  const projectUri = String(project?.v_uri || '')
  const apiProjectUri = toApiUri(projectUri)
  const displayProjectUri = projectUri || toDisplayUri(apiProjectUri)
  const projectId = String(project?.id || '')
  const projectName = String(project?.name || '')
  const { showToast } = useUIStore()
  const dtoRole = useAuthStore((s) => String(s.user?.dto_role || 'PUBLIC').toUpperCase())
  const forcedBoqProjectUri = displayProjectUri ? displayProjectUri.replace(/\/$/, '') : 'v://cn.zhongbei/highway'
  const forcedBoqRootBase = `${forcedBoqProjectUri}/boq`
  const apiBoqRootBase = apiProjectUri ? `${apiProjectUri.replace(/\/$/, '')}/boq` : toApiUri(forcedBoqRootBase)
  const {
    smuImportGenesis,
    smuImportGenesisAsync,
    smuImportGenesisPreview,
    smuImportGenesisJobPublic,
    smuImportGenesisJobActivePublic,
    smuNodeContext,
    smuExecute,
    smuSign,
    tripGenerateDoc,
    smuFreeze,
    smuRetryErpnext,
    boqRealtimeStatus,
    evidenceCenterEvidence,
    publicVerifyDetail,
    downloadEvidenceCenterZip,
    triproleExecute,
    applyVariationDelta,
    scanConfirmSignature,
    replayOfflinePackets,
    exportDocFinal,
    finalizeDocFinal,
    unitMerkleRoot,
    projectReadinessCheck,
    specdictEvolve,
    specdictExport,
    arOverlay,
  } = useProof()

  const boqFileRef = useRef<HTMLInputElement | null>(null)
  const evidenceFileRef = useRef<HTMLInputElement | null>(null)
  const offlineImportRef = useRef<HTMLInputElement | null>(null)
  const previewScrollRef = useRef<HTMLDivElement | null>(null)
  const pdfCanvasRef = useRef<HTMLCanvasElement | null>(null)
  const contractorAnchorRef = useRef<HTMLDivElement | null>(null)
  const supervisorAnchorRef = useRef<HTMLDivElement | null>(null)
  const ownerAnchorRef = useRef<HTMLDivElement | null>(null)
  const autoRejectRef = useRef('')
  const {
    ctx,
    setCtx,
    loadingCtx,
    setLoadingCtx,
    contextError,
    setContextError,
    form,
    setForm,
    compType,
    setCompType,
    sampleId,
    setSampleId,
    claimQty,
    setClaimQty,
    executorDid,
    setExecutorDid,
    supervisorDid,
    setSupervisorDid,
    ownerDid,
    setOwnerDid,
    lat,
    setLat,
    lng,
    setLng,
    evidenceCenter,
    setEvidenceCenter,
    evidenceCenterLoading,
    setEvidenceCenterLoading,
    evidenceCenterError,
    setEvidenceCenterError,
    erpRetrying,
    setErpRetrying,
    erpRetryMsg,
    setErpRetryMsg,
    fingerprintOpen,
    setFingerprintOpen,
    draftStamp,
    setDraftStamp,
    disputeProofId,
    setDisputeProofId,
    disputeResolutionNote,
    setDisputeResolutionNote,
    disputeResult,
    setDisputeResult,
    copiedMsg,
    setCopiedMsg,
    traceOpen,
    setTraceOpen,
    docModalOpen,
    setDocModalOpen,
    pdfRenderError,
    setPdfRenderError,
    pdfRenderLoading,
    setPdfRenderLoading,
    showAdvancedConsensus,
    setShowAdvancedConsensus,
    showAcceptanceAdvanced,
    setShowAcceptanceAdvanced,
    specdictProjectUris,
    setSpecdictProjectUris,
    specdictMinSamples,
    setSpecdictMinSamples,
    specdictNamespace,
    setSpecdictNamespace,
    specdictCommit,
    setSpecdictCommit,
    arRadius,
    setArRadius,
    arLimit,
    setArLimit,
    p2pNodeId,
    p2pPeers,
    setP2pPeers,
    p2pAutoSync,
    setP2pAutoSync,
    p2pLastSync,
    setP2pLastSync,
    docFinalPassphrase,
    setDocFinalPassphrase,
    docFinalIncludeUnsettled,
    setDocFinalIncludeUnsettled,
    nowTick,
    setNowTick,
  } = useSovereignWorkbenchLocalState({
    apiProjectUri,
    displayProjectUri,
  })

  const {
    evidence,
    evidenceName,
    evidenceOpen,
    evidenceFocus,
    hashing,
    resetEvidence,
    onEvidence,
    openEvidencePreview,
    closeEvidencePreview,
  } = useEvidenceFiles()
  const tripFlowState = useSovereignTripFlowState()
  const {
    executing,
    rejecting,
    execRes,
    signOpen,
    setSignOpen,
    signStep,
    signing,
    signRes,
    mockGenerating,
    mockDocRes,
    consensusContractorValue,
    setConsensusContractorValue,
    consensusSupervisorValue,
    setConsensusSupervisorValue,
    consensusOwnerValue,
    setConsensusOwnerValue,
    consensusAllowedDeviation,
    setConsensusAllowedDeviation,
    consensusAllowedDeviationPct,
    setConsensusAllowedDeviationPct,
    signFocus,
    setSignFocus,
    deltaAmount,
    setDeltaAmount,
    deltaReason,
    setDeltaReason,
    applyingDelta,
    variationRes,
    showAdvancedExecution,
    setShowAdvancedExecution,
    deltaModalOpen,
    setDeltaModalOpen,
  } = tripFlowState
  const {
    scanEntryLog,
    meshpegLog,
    formulaLog,
    gatewayLog,
    setScanEntryLog,
    setMeshpegLog,
    setFormulaLog,
    setGatewayLog,
    appendScanEntryLog,
    appendMeshpegLog,
    appendFormulaLog,
    appendGatewayLog,
    reconcileReplayResults,
  } = useEvidenceEventLogs()
  const {
    specdictLoading,
    specdictExporting,
    specdictRes,
    runSpecdictEvolve,
    runSpecdictExport,
    arLoading,
    arRes,
    runArOverlay,
  } = useSpecdictArActions({
    apiProjectUri,
    specdictProjectUris,
    specdictMinSamples,
    specdictNamespace,
    specdictCommit,
    lat,
    lng,
    arRadius,
    arLimit,
    specdictEvolve,
    specdictExport,
    arOverlay,
    showToast,
  })

  useNowTickEffect({
    setNowTick,
  })
  const {
    resetSelectionWorkspace,
    activateTreeNode,
    loadContext,
    retryErpnextPush,
  } = useSovereignContextActions({
    apiProjectUri,
    compType,
    sampleId,
    erpRetrying,
    resetEvidence,
    showToast,
    smuNodeContext,
    smuRetryErpnext,
    setCtx,
    setContextError,
    setForm,
    setCompType,
    setSampleId,
    setClaimQty,
    setLoadingCtx,
    setErpRetrying,
    setErpRetryMsg,
  })

  const {
    fileName,
    importing,
    importJobId,
    importProgress,
    importStatusText,
    importError,
    readinessLoading,
    readinessPercent,
    readinessOverall,
    readinessLayers,
    showRolePlaybook,
    setShowRolePlaybook,
    showLeftSummary,
    setShowLeftSummary,
    nodes,
    setNodes,
    expandedCodes,
    activeUri,
    treeQuery,
    setTreeQuery,
    byUri,
    byCode,
    roots,
    treeSearch,
    runReadinessCheck,
    refreshTreeFromServer,
    onSelectFile,
    loadBuiltinLedger400,
    importGenesis,
    selectNode,
    toggleExpanded,
  } = useSovereignTreeImport({
    apiProjectUri,
    displayProjectUri,
    forcedBoqRootBase,
    apiBoqRootBase,
    projectId,
    showToast,
    projectReadinessCheck,
    boqRealtimeStatus,
    smuImportGenesis,
    smuImportGenesisAsync,
    smuImportGenesisPreview,
    smuImportGenesisJobPublic,
    smuImportGenesisJobActivePublic,
    resetSelectionWorkspace,
    onActivateNode: activateTreeNode,
  })

  const {
    active,
    smuOptions,
    aggMap,
    summary,
  } = useSovereignTreeDerivedState({
    activeUri,
    byUri,
    nodes,
    byCode,
  })
  const sovereignSession = useSovereignSession({
    projectUri,
    apiProjectUri,
    displayProjectUri,
    projectId,
    nodes,
    byCode,
    active,
    ctx,
    execRes,
    signRes,
    dtoRole,
  })
  const {
    nodePathMap,
    activePath,
    boundSpu,
    isContractSpu,
    spuKind,
    spuBadge,
    stepLabel,
    roleAllowed,
    normResolution,
    lifecycle,
  } = sovereignSession
  const activeCode = String(active?.code || '')
  const activeName = String(active?.name || '')
  const activeStatus = String(active?.status || '')
  const activeSpu = String(active?.spu || '')
  const activeUriText = String(active?.uri || '')
  useActiveNodeBroadcastEffect({
    activeCode,
    activeName,
    activeStatus,
    activeSpu,
    activeUri: activeUriText,
    activePath,
    displayProjectUri,
  })
  const {
    effectiveSchema,
    gateStats,
    offlineActorId,
  } = useSovereignWorkbenchInputState({
    ctx,
    active,
    boundSpu,
    isContractSpu,
    form,
    executorDid,
    p2pNodeId,
  })

  const {
    inputProofId,
    verifyUri,
    pdfB64,
    totalHash,
    scanConfirmUri,
    scanConfirmToken,
  } = useSovereignProofChainInputs({
    ctx,
    execRes,
    signRes,
    mockDocRes,
    evidenceCenter,
  })
  const {
    scanPayload,
    setScanPayload,
    scanDid,
    setScanDid,
    scanProofId,
    setScanProofId,
    scanRes,
    scanning,
    scanLockStage,
    scanLockProofId,
    doScanConfirm,
    closeScanLock,
  } = useScanConfirmAction({
    apiProjectUri,
    inputProofId,
    scanConfirmToken,
    lat,
    lng,
    scanConfirmSignature,
    showToast,
  })
  const {
    finalProofId,
    tripStage,
    finalProofReady,
  } = useSovereignProofChainStatus({
    signRes,
    execRes,
    scanRes,
    scanLockProofId,
    verifyUri,
  })
  const isGenesisView = workspaceView === 'genesis'
  const isTripView = workspaceView === 'trip'
  const isAuditView = workspaceView === 'audit'
  const navigateToTrip = onNavigateView ? () => onNavigateView('trip') : undefined
  const navigateToAudit = onNavigateView ? () => onNavigateView('audit') : undefined
  const {
    evidenceTimeline,
    evidenceDocs,
    evidenceItems,
    scanEntryItems,
    meshpegItems,
    formulaItems,
    gatewayItems,
    ledgerSnapshot,
    consensusDispute,
    latestEvidenceNode,
    utxoStatusText,
    docpegRisk,
    docpegRiskScore,
    effectiveRiskScore,
    evidenceCompletenessScore,
    settlementRiskScore,
    assetOrigin,
    assetOriginStatement,
    didReputation,
    didReputationScore,
    didReputationGrade,
    didSamplingMultiplier,
    didHighRiskList,
    sealingTrip,
    sealingPatternId,
    sealingScanHint,
    sealingRows,
    sealingMicrotext,
    disputeOpen,
    disputeProof,
    disputeProofShort,
    disputeConflict,
    disputeDeviation,
    disputeDeviationPct,
    disputeAllowedAbs,
    disputeAllowedPct,
    disputeValues,
  } = useSovereignEvidenceDerivedState({
    evidenceCenter,
    signRes,
    mockDocRes,
    activeStatus,
  })
  const {
    showAllScanEntries,
    setShowAllScanEntries,
    scanEntryLatest,
    scanChainBadge,
    scanEntryActiveOnly,
  } = useSovereignEvidencePanelState({
    activeUri: activeUriText,
    scanEntryItems,
  })
  const {
    evidenceQuery,
    setEvidenceQuery,
    evidenceFilter,
    setEvidenceFilter,
    evidenceScope,
    setEvidenceScope,
    evidenceSmuId,
    setEvidenceSmuId,
    setEvidencePage,
    evidenceCenterFocus,
    evidenceCenterDocFocus,
    openEvidenceFocus,
    closeEvidenceFocus,
    openDocumentFocus,
    closeDocumentFocus,
    evidenceZipDownloading,
    filteredEvidenceItems,
    filteredDocs,
    erpReceiptDoc,
    evidencePageSafe,
    totalEvidencePages,
    evidenceItemsPaged,
    exportEvidenceCenter,
    exportEvidenceCenterCsv,
    downloadEvidenceCenterPackage,
  } = useEvidenceCenterView({
    activeCode,
    apiProjectUri,
    smuOptions,
    evidenceCenter,
    evidenceDocs,
    evidenceItems,
    evidenceTimeline,
    meshpegItems,
    formulaItems,
    gatewayItems,
    ledgerSnapshot,
    docpegRisk,
    didReputation,
    assetOrigin,
    assetOriginStatement,
    sealingTrip,
    totalHash,
    showToast,
    downloadEvidenceCenterZip,
  })
  useDisputeProofAutofillEffect({
    openProofId: String(consensusDispute.open_proof_id || ''),
    disputeProofId,
    setDisputeProofId,
  })
  const activeGenesisSummary = useSovereignActiveGenesisSummary({
    active,
    byCode,
    filteredDocs,
    gateStats,
    summary,
  })
  const {
    evidenceGraphNodes,
    templateDisplay,
    templatePath,
    templateSourceText,
    draftReady,
    previewPdfB64,
    previewIsDraft,
    pdfPage,
    activeSignMarker,
  } = useSovereignWorkbenchViewState({
    active,
    ctx,
    signRes,
    inputProofId,
    verifyUri,
    totalHash,
    filteredDocs,
    evidenceTimeline,
    gateStats: {
      qcCompliant: gateStats.qcCompliant,
      labLatestPass: gateStats.labLatestPass,
      labQualified: gateStats.labQualified,
    },
    signStep,
    draftStamp,
    executorDid,
    supervisorDid,
    ownerDid,
    pdfB64,
    signFocus,
    buildDraftPdfBase64,
  })
  const specBinding = normResolution.specBinding
  const gateBinding = normResolution.gateBinding
  const normRefs = normResolution.normRefs
  const {
    geoAnchor,
    geoDistance,
    temporalWindow,
    geoFenceActive,
    temporalBlocked,
    geoTemporalBlocked,
    specdictRuleTotal,
    specdictHighRisk,
    specdictBestPractice,
    specdictHighRiskItems,
    specdictBestPracticeItems,
    specdictSuccessPatterns,
    specdictWeightEntries,
    specdictBundleUri,
    gateReason,
    displayMeta,
    geoValid,
    geoFenceWarning,
    snappegReady,
    geoFenceStatusText,
    geoFormLocked,
    evidenceLabel,
    evidenceAccept,
    evidenceHint,
    finalPiecePrompt,
    arItems,
    isSpecBound,
  } = useSovereignGeoSpecdictState({
    active,
    ctx,
    lat,
    lng,
    nowTick,
    specdictRes,
    specdictNamespace,
    arRes,
    gateStats,
    form,
    execRes,
    isContractSpu,
    evidence,
    specBinding,
    gateBinding,
  })
  const {
    baselineTotal,
    availableTotal,
    effectiveSpent,
    claimQtyProvided,
    measuredQtyValue,
    effectiveClaimQtyValue,
    consensusBaseValueText,
    consensusConflict,
    consensusMinValueText,
    consensusMaxValueText,
    consensusDeviationText,
    consensusDeviationPercentText,
    consensusAllowedAbsText,
    consensusAllowedPctText,
    consensusConflictSummary,
    exceedBalance,
    deltaSuggest,
    exceedTotalText,
  } = useSovereignConsensusState({
    summary,
    claimQty,
    form,
    effectiveSchema,
    isContractSpu,
    consensus: {
      contractorValue: consensusContractorValue,
      supervisorValue: consensusSupervisorValue,
      ownerValue: consensusOwnerValue,
      allowedDeviation: consensusAllowedDeviation,
      allowedDeviationPct: consensusAllowedDeviationPct,
    },
    identity: {
      executorDid,
      supervisorDid,
      ownerDid,
    },
    context: {
      apiProjectUri,
      activeUri: activeUriText,
    },
    helpers: {
      formatNumber,
    },
  })
  const {
    submitTrip,
    submitTripMock,
    recordRejectTrip,
    doSign,
    applyDelta,
  } = useSovereignTripFlow({
    active,
    apiProjectUri,
    inputProofId,
    isSpecBound,
    roleAllowed,
    compType,
    form,
    effectiveSchema,
    sampleId,
    effectiveClaimQtyValue,
    measuredQtyValue,
    exceedBalance,
    executorDid,
    supervisorDid,
    ownerDid,
    lat,
    lng,
    evidence,
    gateStats,
    geoAnchor,
    templatePath,
    refreshTreeFromServer,
    setNodes,
    setDisputeProofId,
    setShowAdvancedConsensus,
    consensusContractorValue,
    consensusSupervisorValue,
    consensusOwnerValue,
    consensusAllowedDeviation,
    consensusAllowedDeviationPct,
    showToast,
    smuExecute,
    tripGenerateDoc,
    smuSign,
    smuFreeze,
    applyVariationDelta,
    tripState: tripFlowState,
    onMockDocReady: () => setDocModalOpen(true),
  })

  useLabRefreshEffect({
    labQualified: gateStats.labQualified,
    activeIsLeaf: Boolean(active?.isLeaf),
    activeUri,
    apiProjectUri,
    isContractSpu,
    sampleId,
    loadingCtx,
    compType,
    loadContext,
  })

  const { loadEvidenceCenter } = useEvidenceCenterLoader({
    apiProjectUri,
    activeCode,
    activeIsLeaf: Boolean(active?.isLeaf),
    activeUri: activeUriText,
    evidenceScope,
    evidenceSmuId,
    finalProofId,
    inputProofId,
    evidenceCenterEvidence,
    publicVerifyDetail,
    showToast,
    setEvidenceCenter,
    setEvidenceCenterLoading,
    setEvidenceCenterError,
    scanEntryLog,
    meshpegLog,
    formulaLog,
    gatewayLog,
    setScanEntryLog,
    setMeshpegLog,
    setFormulaLog,
    setGatewayLog,
  })
  const {
    offlinePackets,
    offlineType,
    setOfflineType,
    offlineReplay,
    offlineImporting,
    offlineImportName,
    offlineSyncConflicts,
    isOnline,
    queueOfflinePacket,
    clearOfflinePackets,
    exportOfflinePackets,
    importOfflinePackets,
    simulateP2PSync,
  } = useOfflinePackets({
    storageKey: OFFLINE_KEY,
    autoReplayEnabled: p2pAutoSync,
    replayDefaultExecutorUri: apiProjectUri ? `${apiProjectUri.replace(/\/$/, '')}/role/contractor/mobile/` : '',
    replayOfflinePackets,
    onReplayResults: reconcileReplayResults,
    onReplayPatched: loadEvidenceCenter,
    onSyncRecorded: (iso) => setP2pLastSync(iso),
    showToast,
  })
  const offlineCount = offlinePackets.length
  const {
    disputeResolving,
    disputeResolveRes,
    resolveDispute,
    docFinalExporting,
    docFinalFinalizing,
    docFinalRes,
    archiveLocked,
    exportProjectDocFinal,
    finalizeProjectDocFinal,
    assetAppraising,
    assetAppraisal,
    buildAssetAppraisal,
  } = useAuditFinalizeActions({
    apiProjectUri,
    projectName,
    ownerDid,
    lat,
    lng,
    disputeProofId,
    disputeResolutionNote,
    disputeResult,
    docFinalPassphrase,
    docFinalIncludeUnsettled,
    activeUri: activeUriText,
    finalProofReady,
    consensusConflict,
    disputeOpen,
    docpegRiskScore,
    totalHash,
    evidenceCount: evidenceItems.length,
    documentCount: evidenceDocs.length,
    finalProofId,
    inputProofId,
    triproleExecute,
    exportDocFinal,
    finalizeDocFinal,
    loadEvidenceCenter,
    showToast,
  })
  useWorkspaceSnapshotEffect({
    onContextChange,
    activePath,
    displayProjectUri,
    lifecycle,
    activeCode,
    activeStatus,
    totalHash: String(totalHash || ''),
    verifyUri: String(verifyUri || ''),
    finalProofReady,
    isOnline,
    offlineQueueSize: offlineCount,
    disputeOpen: Boolean(asWorkbenchDict(evidenceCenter?.consensusDispute || {}).open),
    disputeProof: String(
      asWorkbenchDict(evidenceCenter?.consensusDispute || {}).open_proof_id
        || asWorkbenchDict(evidenceCenter?.consensusDispute || {}).latest_proof_id
        || '',
    ),
    archiveLocked,
  })

  useGeoFenceToastEffect({
    geoFenceActive,
    activeUri: activeUriText,
    geoTemporalBlocked,
    geoDistance,
    temporalBlocked,
    geoRadiusM: geoAnchor?.radiusM,
    showToast,
  })

  const {
    arFocus,
    arFullscreen,
    arFilterMax,
    arItemsSorted,
    arFilteredItems,
    arPrimary,
    setArFilterMax,
    openArFocus,
    closeArFocus,
    openArFullscreen,
    closeArFullscreen,
    selectArFullscreenItem,
    jumpToArItem,
  } = useSovereignArView({
    arItems,
    byCode,
    byUri,
    selectNode,
    showToast,
  })

  useDocPegPreviewEffects({
    signRes,
    setScanProofId,
    pdfB64,
    setDocModalOpen,
    draftReady,
    draftStamp,
    setDraftStamp,
    activeUri: activeUriText,
    previewPdfB64,
    pdfPage,
    pdfCanvasRef,
    setPdfRenderError,
    setPdfRenderLoading,
    activeSignMarker,
    previewScrollRef,
  })

  const {
    qrSrc,
    docFinalVerifyBaseUrl,
    docFinalAuditUrl,
    docFinalQrSrc,
  } = useSovereignVerifyAssets({
    mockDocRes,
    verifyUri,
    projectId,
  })
  const {
    scrollToSign,
    copyText,
    sealOfflinePacket,
    enqueueScanEntryPacket,
    enqueueTriprolePacket,
  } = useSovereignWorkbenchActions({
    sign: {
      setSignFocus,
      contractorAnchorRef,
      supervisorAnchorRef,
      ownerAnchorRef,
    },
    clipboard: {
      setCopiedMsg,
      showToast,
    },
    offline: {
      activeUri: activeUriText,
      apiProjectUri,
      compType,
      deltaAmount,
      deltaReason,
      evidence,
      executorDid,
      form,
      inputProofId,
      lat,
      lng,
      offlineActorId,
      offlineType,
      queueOfflinePacket,
      sampleId,
    },
    scanEntry: {
      activeUri: activeUriText,
      apiProjectUri,
      inputProofId,
      executorDid,
      lat,
      lng,
      offlineActorId,
      queueOfflinePacket,
      geoDistance,
      geoRadiusM: geoAnchor?.radiusM,
      temporalWindow,
    },
    triprole: {
      activeUri: activeUriText,
      apiProjectUri,
      inputProofId,
      executorDid,
      lat,
      lng,
      offlineActorId,
      queueOfflinePacket,
    },
  })

  const {
    scanEntryAt,
    scanEntryStatus,
    scanEntryToken,
    scanEntryTokenHash,
    scanEntryRequired,
    setScanEntryToken,
    setScanEntryRequired,
    handleScanEntry,
  } = useScanEntryState({
    activeUri: activeUriText,
    geoTemporalBlocked,
    lat,
    lng,
    showToast,
    enqueueScanEntryPacket,
    appendScanEntryLog,
    loadEvidenceCenter,
  })

  const {
    showFingerprintAdvanced,
    setShowFingerprintAdvanced,
    unitProofId,
    setUnitProofId,
    unitMaxRows,
    setUnitMaxRows,
    unitRes,
    unitLoading,
    unitVerifying,
    unitVerifyMsg,
    itemPathSteps,
    unitPathSteps,
    meshpegCloudName,
    setMeshpegCloudName,
    meshpegBimName,
    setMeshpegBimName,
    meshpegRunning,
    meshpegRes,
    formulaExpr,
    setFormulaExpr,
    formulaRunning,
    formulaRes,
    gatewayRes,
    calcUnitMerkle,
    useCurrentProofForUnit,
    exportMerkleJson,
    runMeshpeg,
    runFormulaPeg,
    runGatewaySync,
    verifyUnitMerkle,
  } = useSovereignAdvancedOps({
    apiProjectUri,
    activeCode,
    activeUri: activeUriText,
    inputProofId,
    finalProofId,
    totalHash,
    docpegRiskScore,
    scanEntryLatestProofId: String(scanEntryLatest?.proof_id || ''),
    geoDistance,
    effectiveClaimQtyValue,
    measuredQtyValue,
    ledgerSnapshot,
    unitMerkleRoot,
    enqueueTriprolePacket,
    appendMeshpegLog,
    appendFormulaLog,
    appendGatewayLog,
    showToast,
  })

  const exportP2PManifest = useSovereignP2PManifestExport({
    apiProjectUri,
    p2pNodeId,
    p2pPeers,
    totalHash,
    unitRes,
    offlinePackets,
    offlineSyncConflicts,
  })
  const {
    inputBaseCls,
    inputXsCls,
    btnBlueCls,
    btnGreenCls,
    btnAmberCls,
    btnRedCls,
    panelCls,
    latestProofIdText,
    totalHashShort,
    nearestAnchorText,
    currentSubdivisionText,
    merkleRootText,
  } = buildSovereignWorkbenchDisplayState({
    latestEvidenceNode,
    inputProofId,
    totalHash,
    arPrimary,
    active,
    unitRes,
  })
  const {
    traceOverlayNodes,
    readinessAction,
    componentTypeOptions,
    sovereignValue,
  } = useSovereignWorkbenchSummaryState({
    project: {
      projectUri,
      apiProjectUri,
      displayProjectUri,
      projectId,
      active,
      activeUri,
      activePath,
      boundSpu,
      isContractSpu,
      spuKind,
      spuBadge,
      stepLabel,
      lifecycle,
      nodePathMap,
    },
    identity: {
      dtoRole,
      roleAllowed,
      executorDid,
      supervisorDid,
      ownerDid,
    },
    asset: {
      summary,
      activeGenesisSummary,
      baselineTotal,
      availableTotal,
      effectiveSpent,
      effectiveClaimQtyValue,
      inputProofId,
      finalProofId,
      totalHash,
      verifyUri,
      evidenceCenter,
      sampleId,
    },
    audit: {
      gateStats,
      gateReason,
      exceedBalance,
      snappegReady,
      geoTemporalBlocked,
      normResolution,
      disputeOpen,
      disputeProof,
      archiveLocked,
    },
    ui: {
      compType,
    },
  })
  const {
    handleRunReadinessCheck,
    handleToggleRolePlaybook,
    handleImportGenesis,
    handleLoadBuiltinLedger400,
    handleToggleTreeSummary,
    handleSelectNode,
    handleOpenTrace,
    triggerScanEntry,
    handleLoadContext,
    handleEvidenceUpload,
    handleOpenFingerprint,
    handleApplyDelta,
    handleSuggestDelta,
    handleSubmitTrip,
    handleSubmitTripMock,
    handleRecordRejectTrip,
    handleArCopyText,
    handleArRefresh,
    handleCloseFingerprint,
    handleCloseTrace,
    handleTriggerOfflineImport,
  } = buildSovereignWorkbenchSectionHandlers({
    runReadinessCheck,
    setShowRolePlaybook,
    importGenesis,
    loadBuiltinLedger400,
    setShowLeftSummary,
    selectNode,
    setTraceOpen,
    handleScanEntry,
    activeUri: activeUriText,
    loadContext,
    compType,
    onEvidence,
    setFingerprintOpen,
    applyDelta,
    setDeltaAmount,
    deltaSuggest,
    setDeltaReason,
    setShowAdvancedExecution,
    submitTrip,
    submitTripMock,
    recordRejectTrip,
    copyText,
    runArOverlay,
    offlineImportRef,
  })
  const workbenchShell = buildSovereignWorkbenchShell({
    isGenesisView,
    isTripView,
    isAuditView,
    frameStyleText: WORKBENCH_FRAME_STYLE_TEXT,
    gridOverlayStyle: WORKBENCH_GRID_OVERLAY_STYLE,
  })
  const workbenchPrimary = buildSovereignWorkbenchPrimary({
    hero: {
      activePath,
      displayProjectUri,
      progressPct: summary.pct,
      isOnline,
      offlineCount,
      nodeCount: nodes.length,
      activeCode,
      totalHash,
      isTripView,
      finalProofReady,
      btnBlueCls,
      onNavigateAudit: navigateToAudit,
    },
    genesisOverview: {
      isGenesisView,
      readinessOverall,
      readinessLoading,
      readinessPercent,
      readinessLayers,
      readinessAction,
      showRolePlaybook,
      btnBlueCls,
      btnGreenCls,
      btnAmberCls,
      panelCls,
      apiProjectUri,
      specBinding,
      gateBinding,
      normRefs,
      isSpecBound,
      lifecycle,
      activeCode,
      availableTotal,
      activePath,
      displayProjectUri,
      onRunReadinessCheck: handleRunReadinessCheck,
      onToggleRolePlaybook: handleToggleRolePlaybook,
      onNavigateTrip: navigateToTrip,
      onNavigateAudit: navigateToAudit,
    },
    genesisTree: {
      styles: {
        panelCls,
        inputBaseCls,
        btnBlueCls,
      },
      files: {
        boqFileRef,
        fileName,
      },
      importState: {
        importing,
        importJobId,
        importStatusText,
        importProgress,
        importError,
      },
      tree: {
        showLeftSummary,
        treeQuery,
        treeSearch,
        nodes,
        roots,
        byCode,
        aggMap,
        expandedCodes,
        nodePathMap,
      },
      actions: {
        onSelectFile,
        onImportGenesis: handleImportGenesis,
        onLoadBuiltinLedger400: handleLoadBuiltinLedger400,
        onToggleSummary: handleToggleTreeSummary,
        onTreeQueryChange: setTreeQuery,
        onToggleExpanded: toggleExpanded,
        onSelectNode: handleSelectNode,
      },
    },
    tripWorkbench: {
      styles: {
        panelCls,
        inputBaseCls,
        btnBlueCls,
        btnAmberCls,
        btnGreenCls,
        btnRedCls,
      },
      display: {
        hashing,
        templateDisplay,
        isSpecBound,
        specBinding,
        gateBinding,
        displayMeta,
        componentTypeOptions,
      },
      context: {
        compType,
        loadingCtx,
        contextError,
        sampleId,
        effectiveSchema,
        form,
        normRefs,
      },
      scan: {
        geoFormLocked,
        scanEntryStatus,
        scanEntryAt,
        scanEntryToken,
        scanEntryRequired,
        scanEntryTokenHash,
        scanChainBadge,
        scanEntryLatest,
      },
      evidence: {
        evidence,
        evidenceName,
        evidenceAccept,
        evidenceLabel,
        evidenceHint,
        evidenceFileRef,
      },
      delta: {
        showAdvancedExecution,
        deltaAmount,
        deltaReason,
        applyingDelta,
        variationRes,
        claimQty,
        claimQtyProvided,
        measuredQtyValue,
        deltaSuggest,
      },
      geo: {
        geoValid,
        geoFenceWarning,
        temporalBlocked,
        geoFenceActive,
        geoDistance,
        geoAnchor,
        lat,
        lng,
      },
      execution: {
        tripStage,
        effectiveRiskScore,
        executing,
        mockGenerating,
        rejecting,
      },
      actions: {
        onTraceOpen: handleOpenTrace,
        onScanEntry: triggerScanEntry,
        onScanEntryTokenChange: setScanEntryToken,
        onScanEntryRequiredChange: setScanEntryRequired,
        onSampleIdChange: setSampleId,
        onCompTypeChange: setCompType,
        onExecutorDidChange: setExecutorDid,
        onLoadContext: handleLoadContext,
        onFormChange: setForm,
        onEvidence: handleEvidenceUpload,
        onFingerprintOpen: handleOpenFingerprint,
        onEvidencePreview: openEvidencePreview,
        onDeltaAmountChange: setDeltaAmount,
        onDeltaReasonChange: setDeltaReason,
        onApplyDelta: handleApplyDelta,
        onSuggestDelta: handleSuggestDelta,
        onClaimQtyChange: setClaimQty,
        onSubmitTrip: handleSubmitTrip,
        onSubmitTripMock: handleSubmitTripMock,
        onRecordRejectTrip: handleRecordRejectTrip,
        onLatChange: setLat,
        onLngChange: setLng,
      },
      helpers: {
        sanitizeMeasuredInput,
        metricLabel: toChineseMetricLabel,
        toChineseCompType,
      },
    },
  })
  const { auditActionStyles, overlayArStyles } = buildSovereignWorkbenchSecondaryStylePacks({
    inputBaseCls,
    btnBlueCls,
    btnGreenCls,
    btnAmberCls,
  })
  const workbenchSecondaryAuditShell = buildSovereignWorkbenchSecondaryAuditShell({
    shell: {
      isAuditView,
      panelCls,
      draftReady,
    },
    consensusAudit: {
      visibility: {
        showAdvancedConsensus,
        setShowAdvancedConsensus,
        showAcceptanceAdvanced,
        setShowAcceptanceAdvanced,
      },
      scan: {
        finalPiecePrompt,
        scanConfirmUri,
        scanProofId,
        setScanProofId,
        scanPayload,
        setScanPayload,
        scanDid,
        setScanDid,
        scanConfirmToken,
        scanning,
        scanRes,
        doScanConfirm,
      },
      consensus: {
        minValueText: consensusMinValueText,
        maxValueText: consensusMaxValueText,
        deviationText: consensusDeviationText,
        deviationPercentText: consensusDeviationPercentText,
        consensusAllowedAbsText,
        consensusAllowedPctText,
        consensusConflict,
        consensusConflictSummary,
      },
      dispute: {
        disputeProof,
        disputeOpen,
        disputeProofId,
        setDisputeProofId,
        disputeResolutionNote,
        setDisputeResolutionNote,
        disputeResult,
        setDisputeResult,
        disputeResolving,
        disputeResolveRes,
        resolveDispute,
      },
      docFinal: {
        archiveLocked,
        docFinalPassphrase,
        setDocFinalPassphrase,
        docFinalIncludeUnsettled,
        setDocFinalIncludeUnsettled,
        docFinalExporting,
        docFinalFinalizing,
        docFinalRes,
        docFinalAuditUrl,
        docFinalVerifyBaseUrl,
        verifyUri,
        disputeProofShort,
        offlineQueueSize: offlineCount,
        offlineSyncConflicts,
        apiProjectUri,
        docFinalQrSrc,
        exportProjectDocFinal,
        finalizeProjectDocFinal,
      },
      specdict: {
        specdictProjectUris,
        setSpecdictProjectUris,
        specdictMinSamples,
        setSpecdictMinSamples,
        specdictNamespace,
        setSpecdictNamespace,
        specdictCommit,
        setSpecdictCommit,
        specdictLoading,
        specdictExporting,
        specdictRuleTotal,
        specdictHighRisk,
        specdictBestPractice,
        specdictBundleUri,
        specdictSuccessPatterns,
        specdictHighRiskItems,
        specdictBestPracticeItems,
        specdictWeightEntries,
        specdictRes,
        runSpecdictEvolve,
        runSpecdictExport,
      },
      styles: {
        ...auditActionStyles,
      },
      helpers: {
        copyText,
        describeSpecdictItem,
      },
    },
    advancedOps: {
      visibility: {
        showAdvancedConsensus,
        showFingerprintAdvanced,
        setShowFingerprintAdvanced,
      },
      meshpeg: {
        meshpegCloudName,
        setMeshpegCloudName,
        meshpegBimName,
        setMeshpegBimName,
        meshpegRunning,
        meshpegRes,
        runMeshpeg,
      },
      formula: {
        formulaExpr,
        setFormulaExpr,
        formulaRunning,
        formulaRes,
        runFormulaPeg,
      },
      gateway: {
        gatewayRes,
        runGatewaySync,
      },
      asset: {
        assetAppraising,
        assetAppraisal,
        buildAssetAppraisal,
      },
      ar: {
        arRadius,
        setArRadius,
        arLimit,
        setArLimit,
        arLoading,
        activeUri: activeUriText,
        latestProofId: latestProofIdText,
        totalHashShort,
        nearestAnchorText,
        arItems,
        runArOverlay,
        openArFullscreen,
        openArFocus,
      },
      geo: {
        geoFenceStatusText,
        scanEntryStatus,
        scanEntryRequired,
        scanEntryToken,
        scanChainBadge,
        geoAnchor,
        geoDistance,
        temporalWindow,
        geoTemporalBlocked,
        currentSubdivisionText,
      },
      fingerprint: {
        unitLoading,
        unitProofId,
        setUnitProofId,
        unitMaxRows,
        setUnitMaxRows,
        unitRes,
        unitVerifying,
        unitVerifyMsg,
        itemPathSteps,
        unitPathSteps,
        calcUnitMerkle,
        useCurrentProofForUnit,
        verifyUnitMerkle,
        exportMerkleJson,
      },
      p2p: {
        p2pNodeId,
        offlineQueueSize: offlineCount,
        p2pLastSync,
        p2pAutoSync,
        setP2pAutoSync,
        p2pPeers,
        setP2pPeers,
        merkleRootText,
        exportP2PManifest,
        simulateP2PSync,
      },
      styles: {
        ...auditActionStyles,
      },
      helpers: {
        formatNumber,
        copyText,
        downloadJson,
      },
    },
    auditDocPreview: {
      conflict: {
        consensusConflict,
        disputeOpen,
        disputeProof,
        consensusDeviationText,
        consensusDeviationPercentText,
        consensusAllowedAbsText,
        consensusAllowedPctText,
      },
      document: {
        finalProofReady,
        qrSrc,
        verifyUri,
        finalProofId,
        previewPdfB64,
        pdfB64,
        previewIsDraft,
        tripStage,
        evidenceCount: evidence.length,
        totalHash,
        activeCode,
        activePath,
        activeUri: activeUriText,
        gatePass: gateStats.pass,
        gateTotal: gateStats.total || 0,
        reportedPctText: activeGenesisSummary.reportedPct.toFixed(2),
        activeSignMarker,
        pdfPage,
        templateSourceText,
        pdfRenderLoading,
        pdfRenderError,
        draftReady,
        templateDisplay,
        docModalOpen,
        sampleId,
      },
      identity: {
        signFocus,
        signStep,
        executorDid,
        supervisorDid,
        ownerDid,
        setSupervisorDid,
        setOwnerDid,
      },
      refs: {
        contractorAnchorRef,
        supervisorAnchorRef,
        ownerAnchorRef,
        previewScrollRef,
        pdfCanvasRef,
      },
      styles: {
        inputBaseCls,
      },
      helpers: {
        scrollToSign,
        copyText,
        setDocModalOpen,
      },
    },
  })
  const workbenchSecondaryEvidenceVault = buildSovereignWorkbenchSecondaryEvidenceVault({
    evidenceCenter: {
      evidenceCenterLoading,
      evidenceCenterError,
      evidenceQuery,
      setEvidenceQuery,
      evidenceScope,
      setEvidenceScope,
      evidenceSmuId,
      setEvidenceSmuId,
      evidenceFilter,
      setEvidenceFilter,
      smuOptions,
      filteredEvidenceItems,
      filteredDocs,
      evidenceCompletenessScore,
      settlementRiskScore,
      evidenceGraphNodes,
      ledgerSnapshot,
      meshpegItems,
      formulaItems,
      gatewayItems,
      assetOrigin,
      assetOriginStatement,
      didReputationScore,
      didReputationGrade,
      didSamplingMultiplier,
      didHighRiskList,
      sealingPatternId,
      sealingScanHint,
      sealingMicrotext,
      sealingRows,
      scanEntryActiveOnly,
      evidenceItemsPaged,
      evidencePageSafe,
      setEvidencePage,
      totalEvidencePages,
      latestEvidenceNode,
      utxoStatusText,
      evidenceZipDownloading,
      erpReceiptDoc,
      docpegRisk,
      docpegRiskScore,
      loadEvidenceCenter,
      downloadEvidenceCenterPackage,
      exportEvidenceCenter,
      exportEvidenceCenterCsv,
      openEvidenceFocus,
      openDocumentFocus,
    },
    dispute: {
      consensusConflict,
      consensusAllowedAbsText,
      consensusAllowedPctText,
      disputeConflict,
      disputeDeviation,
      disputeDeviationPct,
      disputeAllowedAbsRaw: disputeAllowedAbs,
      disputeAllowedPctRaw: disputeAllowedPct,
      disputeValues,
      disputeProof,
      disputeOpen,
      disputeProofShort,
      setShowAdvancedConsensus,
      setDisputeProofId,
    },
    erp: {
      erpRetrying,
      erpRetryMsg,
      retryErpnextPush,
    },
    styles: {
      btnBlueCls,
    },
    helpers: {
      copyText,
    },
  })
  const workbenchSecondaryTripFlowModal = buildSovereignWorkbenchSecondaryTripFlowModal({
    sign: {
      signOpen,
      tripStage,
      signStep,
      signing,
      executorDid,
      supervisorDid,
      ownerDid,
      doSign,
      setSignOpen,
    },
    consensus: {
      consensusContractorValue,
      setConsensusContractorValue,
      consensusSupervisorValue,
      setConsensusSupervisorValue,
      consensusOwnerValue,
      setConsensusOwnerValue,
      consensusAllowedDeviation,
      setConsensusAllowedDeviation,
      consensusAllowedDeviationPct,
      setConsensusAllowedDeviationPct,
      consensusBaseValueText,
      consensusConflict,
      consensusMinValueText,
      consensusMaxValueText,
      consensusDeviationText,
      consensusDeviationPercentText,
      consensusAllowedAbsText,
      consensusAllowedPctText,
    },
    lock: {
      scanLockStage,
      scanLockProofId,
      closeScanLock,
    },
    delta: {
      deltaModalOpen,
      exceedTotalText,
      setShowAdvancedExecution,
      setDeltaModalOpen,
    },
    styles: {
      inputBaseCls,
      btnAmberCls,
    },
  })
  const workbenchSecondaryEvidenceModal = buildSovereignWorkbenchSecondaryEvidenceModal({
    evidencePreview: {
      evidenceOpen,
      evidenceFocus,
      geoTemporalBlocked,
      activeCode,
      activeUri: activeUriText,
      lat,
      lng,
      executorDid,
      sampleId,
      onCloseEvidencePreview: closeEvidencePreview,
    },
    evidenceCenter: {
      evidenceCenterFocus,
      evidenceCenterDocFocus,
      onCloseEvidenceFocus: closeEvidenceFocus,
      onCloseDocumentFocus: closeDocumentFocus,
    },
  })
  const workbenchSecondaryOverlay = buildSovereignWorkbenchSecondaryOverlay({
    arFocus,
    arFullscreen,
    lat,
    lng,
    arRadius,
    arFilteredItems,
    arItemsSortedCount: arItemsSorted.length,
    arLoading,
    arFilterMax,
    overlayArStyles,
    onArCopyText: handleArCopyText,
    onArFilterMaxChange: setArFilterMax,
    onArRefresh: handleArRefresh,
    onArCloseFocus: closeArFocus,
    onArJumpToItem: jumpToArItem,
    onArCloseFullscreen: closeArFullscreen,
    onArSelectFullscreenItem: selectArFullscreenItem,
    fingerprintOpen,
    evidenceSource: evidence,
    onFingerprintClose: handleCloseFingerprint,
    traceOpen,
    traceNodes: traceOverlayNodes,
    onTraceClose: handleCloseTrace,
    executorDid,
    supervisorDid,
    ownerDid,
    riskScore: effectiveRiskScore,
    totalHash: String(totalHash || ''),
  })
  const workbenchSecondaryOfflineFooter = buildSovereignWorkbenchSecondaryOfflineFooter({
    isOnline,
    offlineCount,
    offlineSyncConflicts,
    offlineType,
    inputXsCls,
    btnBlueCls,
    offlineImporting,
    offlineImportName,
    offlineReplay,
    offlineImportRef,
    onOfflineTypeChange: setOfflineType,
    onSealOfflinePacket: sealOfflinePacket,
    onTriggerImport: handleTriggerOfflineImport,
    onExportOfflinePackets: exportOfflinePackets,
    onClearOfflinePackets: clearOfflinePackets,
    onImportOfflinePackets: importOfflinePackets,
  })
  const workbenchSecondary = buildSovereignWorkbenchSecondary({
    auditShell: workbenchSecondaryAuditShell,
    evidenceVault: workbenchSecondaryEvidenceVault,
    tripFlowModal: workbenchSecondaryTripFlowModal,
    evidenceModal: workbenchSecondaryEvidenceModal,
    workbenchOverlay: workbenchSecondaryOverlay,
    offlineFooter: workbenchSecondaryOfflineFooter,
  })
  const workbenchSectionsProps = buildWorkbenchSectionsProps({
    shell: workbenchShell,
    primary: workbenchPrimary,
    secondary: workbenchSecondary,
  })

  return (
    <ProjectSovereignProvider value={sovereignValue}>
      <NormEngineProvider schema={effectiveSchema} form={form} ctx={ctx} isContractSpu={isContractSpu}>
        <Card title="主权 BOQ 工作台" icon="🔗" style={{ marginBottom: 10 }} className="overflow-hidden sovereign-workbench">
          <SovereignWorkbenchSections {...workbenchSectionsProps} />
        </Card>
      </NormEngineProvider>
    </ProjectSovereignProvider>
  )
}
