"""Template/static dictionaries for SMU flow orchestration."""

from __future__ import annotations

SPU_LIBRARY_ROOT_URI = "v://library/spu"

SPU_TEMPLATE_LIBRARY = {
    "SPU_Physical": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_Physical",
        "label": "实体工程模板",
        "contexts": ["main_beam", "guardrail", "pier", "slab", "generic"],
        "geometry": {
            "variables": [
                {"key": "length", "label": "长度", "unit": "m", "required": False},
                {"key": "width", "label": "宽度", "unit": "m", "required": False},
                {"key": "height", "label": "高度", "unit": "m", "required": False},
            ],
        },
        "formula": {
            "name": "generic_quantity",
            "expression": "length * width * height",
            "variables": ["length", "width", "height"],
            "fallback_expression": "quantity",
            "quantity_aliases": ["claim_quantity", "measured_value", "design_quantity", "approved_quantity"],
            "quantity_unit": "m3",
            "tolerance_ratio": 0.08,
            "description": "默认实体工程量核算",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#generic"],
        "form_schema": [
            {"field": "design_value", "label": "Design Value", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "measured_value", "label": "Measured Value", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "allowed_deviation", "label": "Allowed Deviation", "unit": "", "operator": "present", "default": "", "source": "Field"},
        ],
    },
    "SPU_Reinforcement": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_Reinforcement",
        "label": "钢筋质检模板",
        "contexts": ["main_beam", "guardrail", "pier", "generic"],
        "geometry": {
            "variables": [
                {"key": "length", "label": "钢筋长度", "unit": "m", "required": False},
                {"key": "unit_weight", "label": "单位重", "unit": "kg/m", "required": False},
                {"key": "count", "label": "根数", "unit": "根", "required": False},
            ],
        },
        "formula": {
            "name": "rebar_weight",
            "expression": "length * unit_weight * count",
            "variables": ["length", "unit_weight", "count"],
            "fallback_expression": "quantity",
            "quantity_aliases": ["claim_quantity", "measured_value", "design_quantity", "approved_quantity"],
            "quantity_unit": "kg",
            "tolerance_ratio": 0.05,
            "description": "钢筋理论重量核算",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#rebar"],
        "form_schema": [
            {
                "field": "design_value",
                "label": "Design Value",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Field",
            },
            {
                "field": "measured_value",
                "label": "Measured Value",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Field",
            },
            {
                "field": "allowed_deviation",
                "label": "Allowed Deviation",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Field",
            },
            {
                "field": "yield_strength",
                "label": "Yield Strength",
                "unit": "MPa",
                "operator": ">=",
                "default": "400",
                "source": "SpecDict",
            },
            {
                "field": "spacing_deviation",
                "label": "Spacing Deviation",
                "unit": "mm",
                "operator": "range",
                "default": "-10~10",
                "source": "SpecDict",
                "point_count": 5,
            },
            {
                "field": "cover_thickness",
                "label": "Cover Thickness",
                "unit": "mm",
                "operator": "range",
                "default": "20~60",
                "source": "SpecDict",
                "point_count": 5,
            },
        ],
    },
    "SPU_Concrete": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_Concrete",
        "label": "混凝土质检模板",
        "contexts": ["main_beam", "pier", "slab", "generic"],
        "geometry": {
            "variables": [
                {"key": "length", "label": "长度", "unit": "m", "required": False},
                {"key": "width", "label": "宽度", "unit": "m", "required": False},
                {"key": "height", "label": "高度", "unit": "m", "required": False},
            ],
        },
        "formula": {
            "name": "concrete_volume",
            "expression": "length * width * height",
            "variables": ["length", "width", "height"],
            "fallback_expression": "quantity",
            "quantity_aliases": ["claim_quantity", "measured_value", "design_quantity", "approved_quantity"],
            "quantity_unit": "m3",
            "tolerance_ratio": 0.06,
            "description": "混凝土方量核算",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#concrete"],
        "form_schema": [
            {
                "field": "design_value",
                "label": "Design Value",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Field",
            },
            {
                "field": "measured_value",
                "label": "Measured Value",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Field",
            },
            {
                "field": "allowed_deviation",
                "label": "Allowed Deviation",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Field",
            },
            {
                "field": "compressive_strength",
                "label": "Compressive Strength",
                "unit": "MPa",
                "operator": ">=",
                "default": "30",
                "source": "SpecDict",
                "point_count": 3,
            },
            {
                "field": "slump",
                "label": "Slump",
                "unit": "mm",
                "operator": "range",
                "default": "120~220",
                "source": "SpecDict",
                "point_count": 3,
            },
        ],
    },
    "SPU_Contract": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_Contract",
        "label": "合同凭证模板",
        "contexts": ["generic"],
        "geometry": {"variables": []},
        "formula": {
            "name": "contract_amount",
            "expression": "claimed_amount",
            "variables": ["claimed_amount"],
            "quantity_aliases": ["claimed_amount", "claim_quantity", "approved_quantity"],
            "quantity_unit": "CNY",
            "tolerance_ratio": 0.0,
            "description": "合同支付金额核算",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#contract"],
        "form_schema": [
            {
                "field": "voucher_ref",
                "label": "Contract Voucher Ref",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Contract",
            },
            {
                "field": "claimed_amount",
                "label": "Claimed Amount",
                "unit": "CNY",
                "operator": "present",
                "default": "",
                "source": "Contract",
            },
            {
                "field": "payment_cycle",
                "label": "Payment Cycle",
                "unit": "",
                "operator": "present",
                "default": "",
                "source": "Contract",
            },
        ],
    },
    "SPU_Bridge": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_Bridge",
        "label": "桥梁结构模板",
        "contexts": ["main_beam", "pier", "slab", "generic"],
        "geometry": {
            "variables": [
                {"key": "length", "label": "构件长度", "unit": "m", "required": False},
                {"key": "width", "label": "构件宽度", "unit": "m", "required": False},
                {"key": "height", "label": "构件高度", "unit": "m", "required": False},
            ],
        },
        "formula": {
            "name": "bridge_volume",
            "expression": "length * width * height",
            "variables": ["length", "width", "height"],
            "fallback_expression": "quantity",
            "quantity_aliases": ["claim_quantity", "measured_value", "design_quantity", "approved_quantity"],
            "quantity_unit": "m3",
            "tolerance_ratio": 0.05,
            "description": "桥梁构件方量核算（盖梁/墩柱等）",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#bridge"],
        "form_schema": [
            {"field": "design_value", "label": "Design Value", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "measured_value", "label": "Measured Value", "unit": "", "operator": "present", "default": "", "source": "Field", "point_count": 5},
            {"field": "allowed_deviation", "label": "Allowed Deviation", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "cover_thickness", "label": "Cover Thickness", "unit": "mm", "operator": "range", "default": "20~60", "source": "SpecDict", "point_count": 5},
        ],
    },
    "SPU_Landscape": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_Landscape",
        "label": "绿化验收模板",
        "contexts": ["generic"],
        "geometry": {
            "variables": [
                {"key": "length", "label": "绿化长度", "unit": "m", "required": False},
                {"key": "width", "label": "绿化宽度", "unit": "m", "required": False},
            ],
        },
        "formula": {
            "name": "landscape_area",
            "expression": "length * width",
            "variables": ["length", "width"],
            "fallback_expression": "quantity",
            "quantity_aliases": ["claim_quantity", "measured_value", "design_quantity", "approved_quantity"],
            "quantity_unit": "m2",
            "tolerance_ratio": 0.08,
            "description": "绿化面积核算",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#landscape"],
        "form_schema": [
            {"field": "survival_rate", "label": "Survival Rate", "unit": "%", "operator": ">=", "default": "95", "source": "SpecDict"},
            {"field": "coverage_rate", "label": "Coverage Rate", "unit": "%", "operator": ">=", "default": "90", "source": "SpecDict"},
            {"field": "height_range", "label": "Height Deviation", "unit": "cm", "operator": "range", "default": "-5~5", "source": "SpecDict"},
        ],
    },
    "SPU_CapBeam": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_CapBeam",
        "label": "盖梁模板",
        "contexts": ["main_beam", "pier", "generic"],
        "geometry": {
            "variables": [
                {"key": "length", "label": "盖梁长度", "unit": "m", "required": True},
                {"key": "width", "label": "盖梁宽度", "unit": "m", "required": True},
                {"key": "height", "label": "盖梁高度", "unit": "m", "required": True},
            ],
        },
        "formula": {
            "name": "cap_beam_volume",
            "expression": "length * width * height",
            "variables": ["length", "width", "height"],
            "fallback_expression": "quantity",
            "quantity_aliases": ["claim_quantity", "measured_value", "design_quantity", "approved_quantity"],
            "quantity_unit": "m3",
            "tolerance_ratio": 0.05,
            "description": "盖梁实体方量核算",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#cap_beam"],
        "form_schema": [
            {"field": "design_value", "label": "Design Value", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "measured_value", "label": "Measured Value", "unit": "", "operator": "present", "default": "", "source": "Field", "point_count": 5},
            {"field": "allowed_deviation", "label": "Allowed Deviation", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "cover_thickness", "label": "Cover Thickness", "unit": "mm", "operator": "range", "default": "20~60", "source": "SpecDict", "point_count": 5},
        ],
    },
    "SPU_PileFoundation": {
        "library_uri": f"{SPU_LIBRARY_ROOT_URI}/SPU_PileFoundation",
        "label": "桩基模板",
        "contexts": ["pier", "generic"],
        "geometry": {
            "variables": [
                {"key": "pile_length", "label": "桩长", "unit": "m", "required": False},
                {"key": "pile_diameter", "label": "桩径", "unit": "m", "required": False},
                {"key": "pile_count", "label": "桩数", "unit": "根", "required": False},
            ],
        },
        "formula": {
            "name": "pile_volume",
            "expression": "3.1415926 * (pile_diameter / 2) * (pile_diameter / 2) * pile_length * pile_count",
            "variables": ["pile_diameter", "pile_length", "pile_count"],
            "fallback_expression": "quantity",
            "quantity_aliases": ["claim_quantity", "measured_value", "design_quantity", "approved_quantity"],
            "quantity_unit": "m3",
            "tolerance_ratio": 0.06,
            "description": "桩基理论方量核算",
        },
        "normpeg_refs": ["v://norm/JTG/F80/1-2017#pile_foundation"],
        "form_schema": [
            {"field": "design_value", "label": "Design Value", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "measured_value", "label": "Measured Value", "unit": "", "operator": "present", "default": "", "source": "Field", "point_count": 3},
            {"field": "allowed_deviation", "label": "Allowed Deviation", "unit": "", "operator": "present", "default": "", "source": "Field"},
            {"field": "integrity_grade", "label": "Integrity Grade", "unit": "", "operator": "present", "default": "I", "source": "SpecDict"},
        ],
    },
}

SPU_NAME_HINTS = {
    "SPU_CapBeam": ("盖梁", "capbeam", "cap beam", "pier cap"),
    "SPU_PileFoundation": ("桩基", "灌注桩", "钻孔桩", "pile"),
    "SPU_Reinforcement": ("钢筋", "rebar", "reinforcement"),
    "SPU_Concrete": ("混凝土", "砼", "concrete"),
    "SPU_Landscape": ("绿化", "种植", "landscape"),
    "SPU_Bridge": ("桥", "bridge"),
}


HEADER_ALIASES = {
    "item_no": {
        "子目号",
        "子目號",
        "子目编号",
        "子目編號",
        "子目编码",
        "子目編碼",
        "细目号",
        "細目號",
        "细目编号",
        "細目編號",
        "清单编码",
        "清單編碼",
        "清单编号",
        "清單編號",
        "细目",
        "細目",
        "子目",
        "itemno",
        "item_no",
        "itemcode",
        "item",
    },
    "name": {
        "子目名称",
        "子目名稱",
        "细目名称",
        "細目名稱",
        "清单名称",
        "清單名稱",
        "名称",
        "名稱",
        "项目名称",
        "項目名稱",
        "itemname",
        "name",
    },
    "unit": {"单位", "單位", "计量单位", "計量單位", "unit"},
    "division": {"分部工程", "分部", "division"},
    "subdivision": {"分项工程", "分項工程", "子分项", "子分項", "subdivision"},
    "hierarchy": {"所属分部分项层级", "所屬分部分項層級", "分部分项层级", "分部分項層級", "层级", "層級", "hierarchy", "wbs"},
    "design_quantity": {
        "设计数量",
        "設計數量",
        "设计工程量",
        "設計工程量",
        "设计量",
        "設計量",
        "施工图数量",
        "施工圖數量",
        "工程量",
        "designqty",
        "designquantity",
    },
    "unit_price": {"单价", "單價", "综合单价", "綜合單價", "价格", "價格", "price", "unitprice"},
    "approved_quantity": {
        "批复数量",
        "批復數量",
        "批复工程量",
        "批復工程量",
        "审批数量",
        "審批數量",
        "审批工程量",
        "審批工程量",
        "批准数量",
        "批准數量",
        "批准工程量",
        "批准工程量",
        "合同数量",
        "合同數量",
        "合同工程量",
        "审定数量",
        "審定數量",
        "审定工程量",
        "審定工程量",
        "approvedqty",
        "approvedquantity",
    },
    "approved_amount": {
        "批复金额",
        "批復金額",
        "批复合价",
        "批復合價",
        "审定金额",
        "審定金額",
        "审定合价",
        "審定合價",
        "批准金额",
        "批准金額",
        "合同金额",
        "合同金額",
        "合同合价",
        "合同合價",
        "合价",
        "合價",
        "总价",
        "總價",
        "总额",
        "總額",
        "金额",
        "金額",
    },
    "remark": {"备注", "備註", "remark"},
}

NORMREF_BY_PREFIX = {
    "401": ["JTG F80/1-2017"],
    "403": ["JTG F80/1-2017"],
    "405": ["JTG F80/1-2017"],
    "600": ["JTG F80/1-2017"],
    "702": ["JTG F80/1-2017"],
}

ROLE_ALLOW_BY_PREFIX = {
    "401": ["SUPERVISOR", "OWNER"],
    "403": ["AI", "SUPERVISOR", "OWNER"],
    "405": ["AI", "SUPERVISOR", "OWNER"],
    "101": ["SUPERVISOR", "OWNER"],
    "102": ["SUPERVISOR", "OWNER"],
    "600": ["SUPERVISOR", "OWNER"],
    "702": ["SUPERVISOR", "OWNER"],
}

__all__ = [
    "HEADER_ALIASES",
    "NORMREF_BY_PREFIX",
    "ROLE_ALLOW_BY_PREFIX",
    "SPU_LIBRARY_ROOT_URI",
    "SPU_NAME_HINTS",
    "SPU_TEMPLATE_LIBRARY",
]
