import { useCallback } from 'react'

import { useTripAutoDocEffect, useTripExceedBalanceEffect } from './tripFlowEffects'
import { runTripGenerateDoc } from './tripFlowDocpeg'
import { runTripReject } from './tripFlowReject'
import { runTripSubmit } from './tripFlowSubmit'
import { runTripApplyDelta } from './tripFlowDelta'
import { runTripSign } from './tripFlowSign'
import type { UseSovereignTripFlowArgs } from './tripFlowTypes'
import { extractApprovedProofId, hasDocPreview } from './tripFlowUtils'
export { useSovereignTripFlowState } from './useSovereignTripFlowState'
export type { SovereignTripFlowState } from './useSovereignTripFlowState'

export function useSovereignTripFlow({
  active,
  apiProjectUri,
  inputProofId,
  isSpecBound,
  roleAllowed,
  compType,
  form,
  effectiveSchema,
  sampleId,
  effectiveClaimQtyValue,
  measuredQtyValue,
  exceedBalance,
  executorDid,
  supervisorDid,
  ownerDid,
  lat,
  lng,
  evidence,
  gateStats,
  geoAnchor,
  templatePath,
  refreshTreeFromServer,
  setNodes,
  setDisputeProofId,
  setShowAdvancedConsensus,
  consensusContractorValue,
  consensusSupervisorValue,
  consensusOwnerValue,
  consensusAllowedDeviation,
  consensusAllowedDeviationPct,
  showToast,
  smuExecute,
  tripGenerateDoc,
  smuSign,
  smuFreeze,
  applyVariationDelta,
  tripState,
  onMockDocReady,
}: UseSovereignTripFlowArgs) {
  const {
    setExecuting,
    setRejecting,
    execRes,
    setExecRes,
    setSignOpen,
    setSignStep,
    setSigning,
    signRes,
    setSignRes,
    mockGenerating,
    setMockGenerating,
    mockDocRes,
    setMockDocRes,
    setFreezeProof,
    deltaAmount,
    deltaReason,
    setApplyingDelta,
    setVariationRes,
    setShowAdvancedExecution,
    setDeltaModalOpen,
  } = tripState

  const consensusBaseValue = effectiveClaimQtyValue > 0 ? effectiveClaimQtyValue : measuredQtyValue
  const approvedProofId = extractApprovedProofId(signRes)
  const hasPreviewPdf = hasDocPreview({ signRes, mockDocRes })
  useTripExceedBalanceEffect({
    exceedBalance,
    setDeltaModalOpen,
    setShowAdvancedExecution,
  })

  const submitTrip = useCallback(async () => {
    await runTripSubmit({
      active,
      apiProjectUri,
      inputProofId,
      isSpecBound,
      roleAllowed,
      compType,
      form,
      effectiveSchema,
      sampleId,
      effectiveClaimQtyValue,
      exceedBalance,
      executorDid,
      lat,
      lng,
      evidence,
      gateStats,
      showToast,
      setDeltaModalOpen,
      setShowAdvancedExecution,
      setExecuting,
      setExecRes,
      setNodes,
      setSignOpen,
      setSignStep,
      refreshTreeFromServer,
      smuExecute,
    })
  }, [
    active,
    apiProjectUri,
    compType,
    effectiveClaimQtyValue,
    effectiveSchema,
    evidence,
    exceedBalance,
    executorDid,
    form,
    gateStats,
    inputProofId,
    isSpecBound,
    lat,
    lng,
    refreshTreeFromServer,
    roleAllowed,
    setDeltaModalOpen,
    setExecuting,
    setExecRes,
    setNodes,
    setShowAdvancedExecution,
    setSignOpen,
    setSignStep,
    showToast,
    smuExecute,
    sampleId,
  ])

  const submitTripMock = useCallback(async () => {
    await runTripGenerateDoc({
      active,
      apiProjectUri,
      isSpecBound,
      form,
      effectiveSchema,
      sampleId,
      effectiveClaimQtyValue,
      executorDid,
      lat,
      lng,
      geoAnchor,
      evidence,
      showToast,
      tripGenerateDoc,
      setMockGenerating,
      setMockDocRes,
      onMockDocReady,
    })
  }, [
    active,
    apiProjectUri,
    effectiveClaimQtyValue,
    effectiveSchema,
    evidence,
    executorDid,
    form,
    geoAnchor,
    isSpecBound,
    lat,
    lng,
    onMockDocReady,
    sampleId,
    setMockDocRes,
    setMockGenerating,
    showToast,
    tripGenerateDoc,
  ])

  useTripAutoDocEffect({
    approvedProofId,
    hasPreviewPdf,
    mockGenerating,
    activeIsLeaf: Boolean(active?.isLeaf),
    isSpecBound,
    submitTripMock,
  })

  const recordRejectTrip = useCallback(async () => {
    await runTripReject({
      active,
      apiProjectUri,
      inputProofId,
      compType,
      form,
      effectiveSchema,
      sampleId,
      executorDid,
      lat,
      lng,
      evidence,
      gateStats,
      refreshTreeFromServer,
      showToast,
      smuExecute,
      setRejecting,
      setExecRes,
    })
  }, [
    active,
    apiProjectUri,
    compType,
    effectiveSchema,
    evidence,
    executorDid,
    form,
    gateStats.labLatestHash,
    gateStats.labLatestPass,
    inputProofId,
    lat,
    lng,
    refreshTreeFromServer,
    sampleId,
    setExecRes,
    setRejecting,
    showToast,
    smuExecute,
  ])

  const doSign = useCallback(async () => {
    await runTripSign({
      active,
      execRes,
      apiProjectUri,
      templatePath,
      executorDid,
      supervisorDid,
      ownerDid,
      lat,
      lng,
      consensusBaseValue,
      consensusContractorValue,
      consensusSupervisorValue,
      consensusOwnerValue,
      consensusAllowedDeviation,
      consensusAllowedDeviationPct,
      showToast,
      smuSign,
      smuFreeze,
      setSigning,
      setSignStep,
      setDisputeProofId,
      setShowAdvancedConsensus,
      setSignRes,
      setNodes,
      setFreezeProof,
      setSignOpen,
    })
  }, [
    active,
    apiProjectUri,
    consensusAllowedDeviation,
    consensusAllowedDeviationPct,
    consensusBaseValue,
    consensusContractorValue,
    consensusOwnerValue,
    consensusSupervisorValue,
    execRes,
    executorDid,
    lat,
    lng,
    ownerDid,
    setDisputeProofId,
    setFreezeProof,
    setNodes,
    setShowAdvancedConsensus,
    setSignOpen,
    setSignRes,
    setSignStep,
    setSigning,
    showToast,
    smuFreeze,
    smuSign,
    supervisorDid,
    templatePath,
  ])

  const applyDelta = useCallback(async () => {
    await runTripApplyDelta({
      active,
      apiProjectUri,
      deltaAmount,
      deltaReason,
      executorDid,
      lat,
      lng,
      showToast,
      applyVariationDelta,
      setApplyingDelta,
      setNodes,
      setVariationRes,
    })
  }, [
    active,
    apiProjectUri,
    applyVariationDelta,
    deltaAmount,
    deltaReason,
    executorDid,
    lat,
    lng,
    setApplyingDelta,
    setNodes,
    setVariationRes,
    showToast,
  ])

  return {
    submitTrip,
    submitTripMock,
    recordRejectTrip,
    doSign,
    applyDelta,
  }
}
