"""Proof request model modules grouped by domain concern."""

from services.api.domain.proof.schema_models.component_models import (
    ComponentBOMItemBody,
    ComponentBOQItemBody,
    ComponentMaterialBindingBody,
    ComponentMaterialInputBody,
    ComponentNodeBody,
    ComponentUTXOVerifyBody,
)
from services.api.domain.proof.schema_models.documents_models import (
    DocAutoClassifyBody,
    DocPegSpecIRV11Body,
    DocNodeAutoGenerateBody,
    DocNodeCreateBody,
    DocSpecBodyV11,
    DocSpecGateV11,
    DocSpecHeaderV11,
    DocSpecProofV11,
    DocSpecStateV11,
    DocSearchBody,
)
from services.api.domain.proof.schema_models.execution_models import (
    FrequencyCalcBody,
    LabTestRecordBody,
    OfflineProofPacketBody,
    OfflineReplayBody,
    RemediationCloseBody,
    RemediationOpenBody,
    RemediationReinspectBody,
    ScanConfirmBody,
    SensorIngestBody,
    TransferAssetBody,
    TripRoleExecuteBody,
    VariationApplyBody,
)
from services.api.domain.proof.schema_models.finance_models import (
    DocFinalExportBody,
    DocFinalFinalizeBody,
    PaymentCertificateBody,
    RailPactInstructionBody,
)
from services.api.domain.proof.schema_models.intelligence_models import (
    FinanceProofExportBody,
    NormEvolutionBody,
    OMBundleExportBody,
    OMEventBody,
    PredictiveQualityBody,
    RwaConvertBody,
    SpatialBindBody,
    SpecDictEvolutionBody,
    SpecDictExportBody,
)
from services.api.domain.proof.schema_models.smu_models import (
    SMUExecuteBody,
    SMUFreezeBody,
    SMUSignBody,
    SMUValidateBody,
)
from services.api.domain.proof.schema_models.specification_models import (
    GateRuleGenerateBody,
    GateRuleNormImportBody,
    GateRuleRollbackBody,
    GateRuleSaveBody,
    SpecDictSaveBody,
)
from services.api.domain.proof.schema_models.utxo_models import (
    UTXOAutoSettleBody,
    UTXOConsumeBody,
    UTXOCreateBody,
)

__all__ = [
    "UTXOCreateBody",
    "UTXOConsumeBody",
    "UTXOAutoSettleBody",
    "TripRoleExecuteBody",
    "VariationApplyBody",
    "OfflineProofPacketBody",
    "OfflineReplayBody",
    "ScanConfirmBody",
    "SensorIngestBody",
    "DocFinalExportBody",
    "DocFinalFinalizeBody",
    "PaymentCertificateBody",
    "LabTestRecordBody",
    "FrequencyCalcBody",
    "RemediationOpenBody",
    "RemediationReinspectBody",
    "RemediationCloseBody",
    "RailPactInstructionBody",
    "SpatialBindBody",
    "PredictiveQualityBody",
    "FinanceProofExportBody",
    "RwaConvertBody",
    "OMBundleExportBody",
    "OMEventBody",
    "NormEvolutionBody",
    "SpecDictEvolutionBody",
    "SpecDictExportBody",
    "TransferAssetBody",
    "ComponentBOQItemBody",
    "ComponentBOMItemBody",
    "ComponentMaterialBindingBody",
    "ComponentMaterialInputBody",
    "ComponentNodeBody",
    "ComponentUTXOVerifyBody",
    "GateRuleNormImportBody",
    "GateRuleGenerateBody",
    "GateRuleSaveBody",
    "GateRuleRollbackBody",
    "SpecDictSaveBody",
    "DocAutoClassifyBody",
    "DocNodeCreateBody",
    "DocNodeAutoGenerateBody",
    "DocSearchBody",
    "DocPegSpecIRV11Body",
    "DocSpecHeaderV11",
    "DocSpecGateV11",
    "DocSpecBodyV11",
    "DocSpecProofV11",
    "DocSpecStateV11",
    "SMUExecuteBody",
    "SMUSignBody",
    "SMUValidateBody",
    "SMUFreezeBody",
]
